#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/polaric-aprsd" ] || [ -e "/etc/init/polaric-aprsd.conf" ]; then
	invoke-rc.d polaric-aprsd stop || exit $?
fi
# End automatically added section
